// CrumbKit — Cookie export module
// Supports JSON, Netscape (curl/wget), and cURL formats.

/**
 * Format a Unix timestamp to a localized date string.
 * @param {number|null} expirationDate - Seconds since epoch, or null for session.
 * @returns {string}
 */
function formatExpiry(expirationDate) {
  if (!expirationDate) return 'Session';
  return new Date(expirationDate * 1000).toISOString();
}

/**
 * Download a string as a file.
 * @param {string} content - File content.
 * @param {string} filename - Suggested filename.
 * @param {string} mimeType - MIME type.
 */
function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Get a safe filename from a domain name.
 * @param {string} domain
 * @returns {string}
 */
function domainToFilename(domain) {
  return domain.replace(/[^a-zA-Z0-9.-]/g, '_') || 'cookies';
}

// ─── JSON Export ────────────────────────────────────────────────

/**
 * Export cookies as a JSON string.
 * @param {Object[]} cookies - Normalized cookie objects.
 * @returns {string} Pretty-printed JSON.
 */
export function toJSON(cookies) {
  const exportData = cookies.map((c) => ({
    name: c.name,
    value: c.value,
    domain: c.domain,
    path: c.path,
    secure: c.secure,
    httpOnly: c.httpOnly,
    sameSite: c.sameSite,
    expirationDate: c.expirationDate,
    session: c.session
  }));
  return JSON.stringify(exportData, null, 2);
}

/**
 * Download cookies as a JSON file.
 * @param {Object[]} cookies
 * @param {string} domain - Current site domain, used for filename.
 */
export function downloadJSON(cookies, domain) {
  const json = toJSON(cookies);
  const filename = `${domainToFilename(domain)}_cookies.json`;
  downloadFile(json, filename, 'application/json');
}

// ─── Netscape Export (curl/wget format) ──────────────────────────

/**
 * Export cookies as Netscape HTTP Cookie format.
 * Compatible with curl -b, wget --load-cookies, and yt-dlp --cookies.
 *
 * Format: domain  flag  path  secure  expiration  name  value
 * (tab-separated, with # Netscape HTTP Cookie File header)
 *
 * @param {Object[]} cookies - Normalized cookie objects.
 * @returns {string}
 */
function toNetscape(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file was generated by CrumbKit.',
    '# https://github.com/wayknow/crumbkit',
    '#',
    '# To use with curl:  curl -b cookies.txt https://example.com',
    '# To use with wget:  wget --load-cookies cookies.txt https://example.com',
    ''
  ];

  for (const c of cookies) {
    // Netscape format fields (tab-separated):
    // domain  flag  path  secure  expiration  name  value
    const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = c.path || '/';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    // Netscape uses seconds since epoch; session cookies use 0
    const expiration = c.session ? '0' : String(Math.floor(c.expirationDate || 0));
    const name = c.name;
    const value = c.value;

    lines.push([domain, flag, path, secure, expiration, name, value].join('\t'));
  }

  return lines.join('\n') + '\n';
}

/**
 * Download cookies in Netscape format.
 * @param {Object[]} cookies
 * @param {string} domain
 */
export function downloadNetscape(cookies, domain) {
  const content = toNetscape(cookies);
  const filename = `${domainToFilename(domain)}_cookies.txt`;
  downloadFile(content, filename, 'text/plain');
}

// ─── cURL Export ─────────────────────────────────────────────────

/**
 * Export cookies as a cURL command string.
 * Creates a ready-to-use curl command with all cookies embedded.
 *
 * @param {Object[]} cookies
 * @param {string} domain - Current site domain.
 * @returns {string} A curl command string.
 */
function toCurl(cookies, tabUrl) {
  const cookieString = cookies
    .filter((c) => c.name)
    .map((c) => `${encodeURIComponent(c.name)}=${encodeURIComponent(c.value)}`)
    .join('; ');

  return `curl -b '${cookieString}' '${tabUrl}'`;
}

/**
 * Download cookies as a cURL command.
 * @param {Object[]} cookies
 * @param {string} domain
 * @param {string} tabUrl - Current tab URL.
 */
export function downloadCurl(cookies, domain, tabUrl) {
  const content = toCurl(cookies, tabUrl);
  downloadFile(content, `${domainToFilename(domain)}_cookies.sh`, 'text/x-shellscript');
}

// ─── Convenience ─────────────────────────────────────────────────

/**
 * Export cookies in the specified format and trigger download.
 * @param {'json'|'netscape'|'curl'} format
 * @param {Object[]} cookies
 * @param {string} domain
 * @param {string} [tabUrl]
 */
export function exportCookies(format, cookies, domain, tabUrl) {
  switch (format) {
    case 'json':
      downloadJSON(cookies, domain);
      break;
    case 'netscape':
      downloadNetscape(cookies, domain);
      break;
    case 'curl':
      downloadCurl(cookies, domain, tabUrl);
      break;
    default:
      console.error(`Unknown export format: ${format}`);
  }
}
